---
- hosts: wallaroo_workers
  remote_user: ubuntu

  tasks:
  - name: load python source
    copy:
      src: "../spamdetector"
      dest: "~"

  - name: pip install requirements
    shell: "pip install --user -r requirements.txt"
    args:
      chdir: "~/spamdetector"

  - name: start wallaroo initializer
    shell: "cd spamdetector && sh run.sh"

- hosts: chat_server
  remote_user: ubuntu

  tasks:

  - name: remove preexisting erlang packages
    apt:
      name: erlang-*
      state: absent
      purge: yes
    become: true

  - name: get chat server build deps in place #(TODO: move this all out to AMI)
    apt:
      name:
        - unixodbc-dev
        - git
        - erlang
    become: true

  - name: ssh keyscan
    shell: "ssh-keyscan github.com >> ~/.ssh/known_hosts"
    args:
      creates: "~/.ssh/known_hosts"

  - name: pull chat server #(THIS IS HACKY, PACKAGE THE SERVER)
    shell: "git clone --depth=1 git@github.com:pzel/mongooseim mongooseim.git"
    args:
      creates: "~/mongooseim.git"

  - name: build chat server #(THIS IS HACKY, PACKAGE THE SERVER)
    shell: "cd mongooseim.git && make rel"
    args:
      creates: "~/mongooseim.git/_build/prod/rel/mongooseim"

  - name: move chat release out to separate directory
    shell: "mv ~/mongooseim.git/_build/prod/rel/mongooseim ~/"
    args:
      creates: "~/mongooseim"

  - name: start chat server
    shell: >
      export WALLAROO_TCP_HOSTPORT={{ groups['wallaroo_workers'][0] }}:5555;
      ~/mongooseim/bin/mongooseim start

    # debug:
    #   msg: >
    #     export WALLAROO_TCP_HOSTPORT={{ groups['wallaroo_workers'][0] }}:5555;
    #     ~/mongooseim/bin/mongooseim start
